package com.springPractice.mapper;

import com.springPractice.Entity.Account;
import java.util.List;
import org.springframework.data.repository.query.Param;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    long countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    int insert(Account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    int insertSelective(Account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    int updateByExampleSelective(@Param("row") Account row, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    int updateByExample(@Param("row") Account row, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    int updateByPrimaryKeySelective(Account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 25 17:48:08 JST 2025
     */
    int updateByPrimaryKey(Account row);
}