package com.springPractice.mapper;

import com.springPractice.Entity.Account;
import com.springPractice.Entity.Fruits;
import com.springPractice.Entity.FruitsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

// MybatisBasDAO
public interface FruitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    long countByExample(FruitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    int deleteByExample(FruitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    int insert(Fruits row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    int insertSelective(Fruits row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    List<Fruits> selectByExample(FruitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    Fruits selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    int updateByExampleSelective(@Param("row") Fruits row, @Param("example") FruitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    int updateByExample(@Param("row") Fruits row, @Param("example") FruitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    int updateByPrimaryKeySelective(Fruits row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    int updateByPrimaryKey(Fruits row);

	void add(Account acc);
}