package com.springPractice.Entity;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.login_name
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.nick_name
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.age
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.location
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.role
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.avatar
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.login_name
     *
     * @return the value of account.login_name
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.login_name
     *
     * @param loginName the value for account.login_name
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.nick_name
     *
     * @return the value of account.nick_name
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.nick_name
     *
     * @param nickName the value for account.nick_name
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.age
     *
     * @return the value of account.age
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.age
     *
     * @param age the value for account.age
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.location
     *
     * @return the value of account.location
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.location
     *
     * @param location the value for account.location
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.role
     *
     * @return the value of account.role
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.role
     *
     * @param role the value for account.role
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.avatar
     *
     * @return the value of account.avatar
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.avatar
     *
     * @param avatar the value for account.avatar
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
}