server:
  port: 8081

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/RBAC_db?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true
    username: root
    password: ildp009-