spring.application.name=SpringMybatisRBAC
config.systemName=待定
#自动补全实体类包名称
mybatis.type-aliases-package=com.springPractice.mapper
#对应的 sql 映射
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml

#MyBatis 显示 SQL 定义日志级别
logging.level.com.springPractice.mapper=debug

#去除缓存
spring.thymeleaf.cache=false

# 自定义文件上传路径 (请根据你的操作系统修改)
file.upload-dir=/Users/yujiazhang/Documents/uploads/

# 切换生产环境
spring.profiles.active=dev