server.port=8083
config.systemName=China Petroleum and Chemical Corporation \u0020\u4e2d\u56fd\u77f3\u5316

# 日志配置

# 设置根日志级别为 INFO (默认)
logging.level.root=INFO

# 设置特定包的日志级别为 DEBUG
# 比如，让你的项目代码输出更详细的日志
logging.level.com.yourcompany.project=DEBUG

# 设置 Spring 框架自身的日志级别，减少噪音
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR

# 配置日志输出到文件
logging.file.name=logs/my-app.log

# (可选) 配置日志文件的滚动策略 (需要更复杂的配置，通常用下面的方式)
# logging.logback.rollingpolicy.* ```