package com.springPractice.Entity;

import java.util.List;
import lombok.Data;

@Data
public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.login_name
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.nick_name
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.age
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.location
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.role
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.avatar
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    private String avatar;
    // 角色
    private List<Role> roleList;
    // 具体的权限
    // 把五张表查出来的结果都放进去, 把上述的内容都存进 Account 里面
    private List<Permission> permissionList;
    // 从 Role 里面再去 get permissionList

    // 从 Role 里面再去 get permissionList

}