package com.springPractice.Entity;
import lombok.Data;

@Data
public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.uni
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private String uni;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.name
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.c
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private Boolean c;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.r
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private Boolean r;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.u
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private Boolean u;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.d
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private Boolean d;
}