package com.springPractice.Entity;
import lombok.Data;

@Data
public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.addAccount
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private String addaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.createTime
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.lastUpdateTime
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private String lastupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.lastUpdateAccount
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private String lastupdateaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.isDeleted
     *
     * @mbg.generated Sat Sep 27 16:59:21 JST 2025
     */
    private String isdeleted;
}