package com.springPractice.Entity;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.roles
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    private String roles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.index
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    private String index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.roles
     *
     * @return the value of menu.roles
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.roles
     *
     * @param roles the value for menu.roles
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    public void setRoles(String roles) {
        this.roles = roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.index
     *
     * @return the value of menu.index
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    public String getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.index
     *
     * @param index the value for menu.index
     *
     * @mbg.generated Thu Jul 17 18:23:59 JST 2025
     */
    public void setIndex(String index) {
        this.index = index;
    }
}