package com.springPractice.mapper;

import com.springPractice.Entity.Account;
import com.springPractice.Entity.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    long countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    int insert(Account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    int insertSelective(Account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    List<Account> selectByExample(com.springPractice.mapper.AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    int updateByExampleSelective(@Param("row") Account row, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    int updateByExample(@Param("row") Account row, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    int updateByPrimaryKeySelective(Account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Aug 23 18:15:09 JST 2025
     */
    int updateByPrimaryKey(Account row);
}