package com.springPractice.Entity;

import java.util.Date;

public class Fruits {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruits.id
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruits.name
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruits.arrived_date
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    private Date arrivedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruits.id
     *
     * @return the value of fruits.id
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruits.id
     *
     * @param id the value for fruits.id
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruits.name
     *
     * @return the value of fruits.name
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruits.name
     *
     * @param name the value for fruits.name
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruits.arrived_date
     *
     * @return the value of fruits.arrived_date
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    public Date getArrivedDate() {
        return arrivedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruits.arrived_date
     *
     * @param arrivedDate the value for fruits.arrived_date
     *
     * @mbg.generated Wed May 14 16:04:04 JST 2025
     */
    public void setArrivedDate(Date arrivedDate) {
        this.arrivedDate = arrivedDate;
    }
}